### ISSUE TITLE
No Python 3.8 support, cannot import name 'clock' from 'time' (unknown location)

### ISSUE THREAD

**Issue by ghost** [Pyroevil/Blender-Molecular-Script#12]
Hello, I cannot import molecular script, Blender 2.8 runs on Python 3.8, which doesn't support time.clock.
`Traceback (most recent call last):
  File "/usr/share/blender/2.81/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/flynn/.config/blender/2.81/scripts/addons/molecular/__init__.py", line 41, in <module>
    from time import clock,sleep,strftime,gmtime
ImportError: cannot import name 'clock' from 'time' (unknown location)`

**Comment by PavelBlend** [comment]
Where did you download the addon from? The most current version is here:
https://github.com/scorpion81/Blender-Molecular-Script/releases

**Comment by ghost** [comment]
Sorry, I didn't find the link with the newest version, thanks!
